# -*- coding: utf-8 -*-
"""LLMoptimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ga_en_xX8M3Gan_YIMO50zYQCAfMorFa
"""

!nvidia-smi
!pip install nvidia-pyindex
!pip install tensorrt==10.0.1
!pip install onnx onnxruntime
!pip install pycuda
!pip install optimum[onnxruntime-gpu]
!pip install transformers numpy

"""
BERT-base (google-bert/bert-base-uncased)
PyTorch FP16 vs TensorRT FP16 inference benchmark
Masked Language Modeling (encoder-only)
"""

import os
import time
import numpy as np
import torch

from transformers import AutoTokenizer, AutoModelForMaskedLM

import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit


# -----------------------
# Config
# -----------------------
MODEL_ID = "google-bert/bert-base-uncased"

ONNX_PATH = "bert_base.onnx"
ENGINE_PATH = "bert_base_fp16.engine"

BATCH = 1
SEQ_LEN = 32

MIN_SHAPE = (1, 8)
OPT_SHAPE = (1, 32)
MAX_SHAPE = (1, 128)

WARMUP = 20
ITERS = 100
TRT_WORKSPACE_GB = 4


# -----------------------
# Utils
# -----------------------
def pad_input(tokenizer, input_ids, seq_len, device=None):
    if device:
        input_ids = input_ids.to(device)

    if input_ids.shape[1] < seq_len:
        pad = torch.full(
            (input_ids.shape[0], seq_len - input_ids.shape[1]),
            tokenizer.pad_token_id,
            dtype=input_ids.dtype,
            device=input_ids.device,
        )
        input_ids = torch.cat([input_ids, pad], dim=1)
    else:
        input_ids = input_ids[:, :seq_len]

    return input_ids


def torch_latency(model, input_ids):
    model.eval()
    with torch.inference_mode():
        for _ in range(WARMUP):
            _ = model(input_ids=input_ids)
        torch.cuda.synchronize()

        t0 = time.time()
        for _ in range(ITERS):
            _ = model(input_ids=input_ids)
        torch.cuda.synchronize()

    return (time.time() - t0) / ITERS


# -----------------------
# ONNX export (CPU, STABLE)
# -----------------------
def export_onnx_cpu(tokenizer, seq_len):
    model = AutoModelForMaskedLM.from_pretrained(MODEL_ID).eval().to("cpu")

    dummy_text = "TensorRT optimization is powerful"
    input_ids = tokenizer(dummy_text, return_tensors="pt").input_ids

    input_ids = pad_input(tokenizer, input_ids, seq_len)

    torch.onnx.export(
        model,
        (input_ids,),
        ONNX_PATH,
        input_names=["input_ids"],
        output_names=["logits"],
        dynamic_axes={
            "input_ids": {0: "batch", 1: "seq_len"},
            "logits": {0: "batch", 1: "seq_len"},
        },
        opset_version=17,
        do_constant_folding=True,
        dynamo=False,
    )


# -----------------------
# TensorRT build (TRT 9/10)
# -----------------------
def build_trt_engine(onnx_path, engine_path):
    logger = trt.Logger(trt.Logger.WARNING)
    builder = trt.Builder(logger)
    runtime = trt.Runtime(logger)

    network = builder.create_network(
        1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )
    parser = trt.OnnxParser(network, logger)

    with open(onnx_path, "rb") as f:
        if not parser.parse(f.read()):
            for i in range(parser.num_errors):
                print(parser.get_error(i))
            raise RuntimeError("ONNX parse failed")

    config = builder.create_builder_config()
    config.set_flag(trt.BuilderFlag.FP16)
    config.set_memory_pool_limit(
        trt.MemoryPoolType.WORKSPACE, TRT_WORKSPACE_GB << 30
    )

    input_name = network.get_input(0).name
    profile = builder.create_optimization_profile()
    profile.set_shape(input_name, MIN_SHAPE, OPT_SHAPE, MAX_SHAPE)
    config.add_optimization_profile(profile)

    serialized_engine = builder.build_serialized_network(network, config)
    if serialized_engine is None:
        raise RuntimeError("TensorRT engine build failed")

    engine = runtime.deserialize_cuda_engine(serialized_engine)

    with open(engine_path, "wb") as f:
        f.write(serialized_engine)

    return engine


# -----------------------
# TensorRT latency
# -----------------------
def trt_latency(engine, input_ids_np):
    context = engine.create_execution_context()

    input_name = engine.get_tensor_name(0)
    output_name = engine.get_tensor_name(1)

    context.set_input_shape(input_name, input_ids_np.shape)
    out_shape = context.get_tensor_shape(output_name)

    d_input = cuda.mem_alloc(input_ids_np.nbytes)

    out_dtype = np.float16 if engine.get_tensor_dtype(output_name) == trt.DataType.HALF else np.float32
    d_output = cuda.mem_alloc(trt.volume(out_shape) * np.dtype(out_dtype).itemsize)

    stream = cuda.Stream()

    context.set_tensor_address(input_name, int(d_input))
    context.set_tensor_address(output_name, int(d_output))

    for _ in range(WARMUP):
        cuda.memcpy_htod_async(d_input, input_ids_np, stream)
        context.execute_async_v3(stream.handle)
    stream.synchronize()

    t0 = time.time()
    for _ in range(ITERS):
        cuda.memcpy_htod_async(d_input, input_ids_np, stream)
        context.execute_async_v3(stream.handle)
    stream.synchronize()

    return (time.time() - t0) / ITERS


# -----------------------
# Main
# -----------------------
def main():
    torch.backends.cudnn.benchmark = True
    device = "cuda"

    print("Loading model:", MODEL_ID)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

    model = AutoModelForMaskedLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float16,
    ).to(device).eval()

    text = "TensorRT optimization is powerful"
    input_ids = tokenizer(text, return_tensors="pt").input_ids
    input_ids = pad_input(tokenizer, input_ids, SEQ_LEN, device=device)

    print("Input shape:", input_ids.shape)

    pt_lat = torch_latency(model, input_ids)
    print(f"PyTorch FP16 latency: {pt_lat * 1000:.3f} ms")

    if not os.path.exists(ONNX_PATH):
        print("Exporting ONNX (CPU)...")
        export_onnx_cpu(tokenizer, SEQ_LEN)

    if not os.path.exists(ENGINE_PATH):
        print("Building TensorRT engine...")
        engine = build_trt_engine(ONNX_PATH, ENGINE_PATH)
    else:
        runtime = trt.Runtime(trt.Logger(trt.Logger.WARNING))
        with open(ENGINE_PATH, "rb") as f:
            engine = runtime.deserialize_cuda_engine(f.read())

    trt_lat = trt_latency(engine, input_ids.cpu().numpy().astype(np.int32))
    print(f"TensorRT FP16 latency: {trt_lat * 1000:.3f} ms")

    print(f"Speedup: {pt_lat / trt_lat:.2f}x")


if __name__ == "__main__":
    main()

import os
import time
import numpy as np
import torch

from transformers import AutoTokenizer, AutoModelForMaskedLM

import onnxruntime as ort
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit


# =========================
# CONFIG
# =========================
MODEL_ID = "google-bert/bert-base-uncased"

ONNX_PATH = "bert_base.onnx"
ENGINE_PATH = "bert_base_fp16.engine"

BATCH = 1
SEQ_LEN = 32

MIN_SHAPE = (1, 8)
OPT_SHAPE = (1, 32)
MAX_SHAPE = (1, 128)

WARMUP = 20
ITERS = 100
TRT_WORKSPACE_GB = 4


# =========================
# UTILS
# =========================
def pad_input(tokenizer, input_ids, seq_len, device=None):
    if device:
        input_ids = input_ids.to(device)

    if input_ids.shape[1] < seq_len:
        pad = torch.full(
            (input_ids.shape[0], seq_len - input_ids.shape[1]),
            tokenizer.pad_token_id,
            dtype=input_ids.dtype,
            device=input_ids.device,
        )
        input_ids = torch.cat([input_ids, pad], dim=1)
    else:
        input_ids = input_ids[:, :seq_len]

    return input_ids


# =========================
# PYTORCH
# =========================
def measure_torch_latency(model, input_ids):
    model.eval()
    with torch.inference_mode():
        for _ in range(WARMUP):
            _ = model(input_ids=input_ids)
        torch.cuda.synchronize()

        t0 = time.time()
        for _ in range(ITERS):
            _ = model(input_ids=input_ids)
        torch.cuda.synchronize()

    latency = (time.time() - t0) / ITERS
    throughput = BATCH / latency
    return latency, throughput


# =========================
# ONNX RUNTIME
# =========================
def export_onnx_cpu(tokenizer):
    print("Exporting ONNX (CPU)...")
    model = AutoModelForMaskedLM.from_pretrained(MODEL_ID).eval().cpu()

    dummy = tokenizer(
        "TensorRT optimization is powerful",
        return_tensors="pt"
    ).input_ids
    dummy = pad_input(tokenizer, dummy, SEQ_LEN)

    torch.onnx.export(
        model,
        (dummy,),
        ONNX_PATH,
        input_names=["input_ids"],
        output_names=["logits"],
        dynamic_axes={
            "input_ids": {0: "batch", 1: "seq_len"},
            "logits": {0: "batch", 1: "seq_len"},
        },
        opset_version=17,
        do_constant_folding=True,
        dynamo=False,
    )


def measure_onnxruntime_latency(onnx_path, input_ids_np):
    sess = ort.InferenceSession(
        onnx_path,
        providers=["CUDAExecutionProvider"]
    )

    input_name = sess.get_inputs()[0].name

    for _ in range(WARMUP):
        sess.run(None, {input_name: input_ids_np})

    t0 = time.time()
    for _ in range(ITERS):
        sess.run(None, {input_name: input_ids_np})

    latency = (time.time() - t0) / ITERS
    throughput = BATCH / latency
    return latency, throughput


# =========================
# TENSORRT
# =========================
def build_trt_engine(onnx_path):
    print("Building TensorRT engine (FP16)...")

    logger = trt.Logger(trt.Logger.WARNING)
    builder = trt.Builder(logger)
    runtime = trt.Runtime(logger)

    network = builder.create_network(
        1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )
    parser = trt.OnnxParser(network, logger)

    with open(onnx_path, "rb") as f:
        if not parser.parse(f.read()):
            for i in range(parser.num_errors):
                print(parser.get_error(i))
            raise RuntimeError("ONNX parse failed")

    config = builder.create_builder_config()
    config.set_flag(trt.BuilderFlag.FP16)
    config.set_memory_pool_limit(
        trt.MemoryPoolType.WORKSPACE,
        TRT_WORKSPACE_GB << 30
    )

    input_name = network.get_input(0).name
    profile = builder.create_optimization_profile()
    profile.set_shape(input_name, MIN_SHAPE, OPT_SHAPE, MAX_SHAPE)
    config.add_optimization_profile(profile)

    serialized_engine = builder.build_serialized_network(network, config)
    if serialized_engine is None:
        raise RuntimeError("TensorRT engine build failed")

    with open(ENGINE_PATH, "wb") as f:
        f.write(serialized_engine)

    return runtime.deserialize_cuda_engine(serialized_engine)


def measure_trt_latency(engine, input_ids_np):
    context = engine.create_execution_context()

    input_name = engine.get_tensor_name(0)
    output_name = engine.get_tensor_name(1)

    context.set_input_shape(input_name, input_ids_np.shape)
    out_shape = context.get_tensor_shape(output_name)

    d_input = cuda.mem_alloc(input_ids_np.nbytes)
    output_size = int(np.prod(out_shape)) * np.dtype(np.float16).itemsize
    d_output = cuda.mem_alloc(output_size)

    stream = cuda.Stream()

    context.set_tensor_address(input_name, int(d_input))
    context.set_tensor_address(output_name, int(d_output))

    for _ in range(WARMUP):
        cuda.memcpy_htod_async(d_input, input_ids_np, stream)
        context.execute_async_v3(stream.handle)
    stream.synchronize()

    t0 = time.time()
    for _ in range(ITERS):
        cuda.memcpy_htod_async(d_input, input_ids_np, stream)
        context.execute_async_v3(stream.handle)
    stream.synchronize()

    latency = (time.time() - t0) / ITERS
    throughput = BATCH / latency
    return latency, throughput


# =========================
# MAIN
# =========================
def main():
    torch.backends.cudnn.benchmark = True
    device = "cuda"

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

    model = AutoModelForMaskedLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float16
    ).to(device).eval()

    text = "TensorRT optimization is powerful"
    input_ids = tokenizer(text, return_tensors="pt").input_ids
    input_ids = pad_input(tokenizer, input_ids, SEQ_LEN, device=device)

    print("Input shape:", input_ids.shape)

    # PyTorch
    pt_lat, pt_thr = measure_torch_latency(model, input_ids)
    print(f"PyTorch FP16 latency: {pt_lat*1000:.3f} ms | Throughput: {pt_thr:.1f} seq/s")

    # ONNX Runtime
    if not os.path.exists(ONNX_PATH):
        export_onnx_cpu(tokenizer)

    ort_lat, ort_thr = measure_onnxruntime_latency(
        ONNX_PATH,
        input_ids.cpu().numpy().astype(np.int64)
    )
    print(f"ONNX Runtime CUDA latency: {ort_lat*1000:.3f} ms | Throughput: {ort_thr:.1f} seq/s")

    # TensorRT
    if os.path.exists(ENGINE_PATH):
        runtime = trt.Runtime(trt.Logger(trt.Logger.WARNING))
        with open(ENGINE_PATH, "rb") as f:
            engine = runtime.deserialize_cuda_engine(f.read())
    else:
        engine = build_trt_engine(ONNX_PATH)

    trt_lat, trt_thr = measure_trt_latency(
        engine,
        input_ids.cpu().numpy().astype(np.int32)
    )
    print(f"TensorRT FP16 latency: {trt_lat*1000:.3f} ms | Throughput: {trt_thr:.1f} seq/s")

    print("\n===== SPEEDUPS =====")
    print(f"ONNX vs PyTorch: {pt_lat / ort_lat:.2f}x")
    print(f"TensorRT vs PyTorch: {pt_lat / trt_lat:.2f}x")


if __name__ == "__main__":
    main()