# -*- coding: utf-8 -*-
"""MobileNetCUDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0cZKc3kIpNpAwstUGtqNELfNhUv1OSb
"""

!nvidia-smi

!pip install nvidia-pyindex
!pip install tensorrt==10.0.1
!pip install onnx onnxruntime

import tensorrt as trt

onnx_file = "MobileNet-v2.onnx"
engine_file = "MobileNet-v2.engine"

logger = trt.Logger(trt.Logger.INFO)
builder = trt.Builder(logger)

# TRT10: EXPLICIT_BATCH flag
explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
network = builder.create_network(explicit_batch_flag)

parser = trt.OnnxParser(network, logger)

print("Parsing ONNX...")
with open(onnx_file, "rb") as f:
    if not parser.parse(f.read()):
        print("ONNX PARSE FAILED")
        for i in range(parser.num_errors):
            print(parser.get_error(i))
        raise SystemExit

# TRT 10.14 config
config = builder.create_builder_config()

# NEW API: memory pool limit
config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)  # 1GB

# Enable FP16
if builder.platform_has_fast_fp16:
    config.set_flag(trt.BuilderFlag.FP16)

print("Building serialized engine (TRT 10.14)...")
engine_serialized = builder.build_serialized_network(network, config)

if engine_serialized is None:
    raise RuntimeError("ENGINE BUILD FAILED")

print("Saving engine...")
with open(engine_file, "wb") as f:
    f.write(engine_serialized)

print("DONE — Saved:", engine_file)

import numpy as np
import tensorrt as trt
from cuda import cudart
import time

TRT_LOGGER = trt.Logger(trt.Logger.INFO)

# Load engine
with open("MobileNet-v2.engine", "rb") as f:
    runtime = trt.Runtime(TRT_LOGGER)
    engine = runtime.deserialize_cuda_engine(f.read())

context = engine.create_execution_context()

input_name = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)
              if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT][0]

output_name = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)
               if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT][0]

input_shape = tuple(engine.get_tensor_shape(input_name))
output_shape = tuple(engine.get_tensor_shape(output_name))

# Allocate GPU memory
input_nbytes = np.prod(input_shape) * 4
output_nbytes = np.prod(output_shape) * 4

_, d_input = cudart.cudaMalloc(input_nbytes)
_, d_output = cudart.cudaMalloc(output_nbytes)

# Dummy input
x = np.random.randn(*input_shape).astype(np.float32)

# Warmup
for _ in range(10):
    cudart.cudaMemcpy(d_input, x.ctypes.data, input_nbytes,
                      cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)
    context.set_tensor_address(input_name, d_input)
    context.set_tensor_address(output_name, d_output)
    context.execute_async_v3(0)
    cudart.cudaDeviceSynchronize()

# Benchmark
iterations = 500
start = time.time()

for _ in range(iterations):
    cudart.cudaMemcpy(d_input, x.ctypes.data, input_nbytes,
                      cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)

    context.execute_async_v3(0)
    cudart.cudaDeviceSynchronize()

end = time.time()

avg_latency = (end - start) * 1000 / iterations
throughput = iterations / (end - start)

print(f"Average Latency: {avg_latency:.3f} ms")
print(f"Throughput: {throughput:.2f} FPS")

import time
import numpy as np
import tensorrt as trt
from cuda import cudart

TRT_LOGGER = trt.Logger(trt.Logger.INFO)

def benchmark_trt_engine(
    engine_path,
    input_shape=(1, 3, 224, 224),
    n_warmup=50,
    n_runs=500
):
    """
    Verilen TensorRT engine için ortalama latency ve throughput ölçer.
    input_shape, engine’in beklediği batch, kanal, yükseklik, genişlik
    """
    # Engine yükle
    with open(engine_path, "rb") as f:
        runtime = trt.Runtime(TRT_LOGGER)
        engine = runtime.deserialize_cuda_engine(f.read())
    context = engine.create_execution_context()

    # Input ve output tensor isimleri
    input_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT
    ][0]

    output_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT
    ][0]

    # Gerekirse dinamik shape ayarla
    # Eğer engine dinamik değilse, bu satır zaten geçerli shape olur
    context.set_input_shape(input_name, input_shape)

    output_shape = tuple(context.get_tensor_shape(output_name))

    # GPU memory
    input_nbytes = int(np.prod(input_shape) * 4)    # float32
    output_nbytes = int(np.prod(output_shape) * 4)  # float32

    _, d_input = cudart.cudaMalloc(input_nbytes)
    _, d_output = cudart.cudaMalloc(output_nbytes)

    # Dummy input
    x = np.random.randn(*input_shape).astype(np.float32)

    # Adresleri bir kere bağla
    context.set_tensor_address(input_name, d_input)
    context.set_tensor_address(output_name, d_output)

    # Warmup
    for _ in range(n_warmup):
        cudart.cudaMemcpy(
            d_input,
            x.ctypes.data,
            input_nbytes,
            cudart.cudaMemcpyKind.cudaMemcpyHostToDevice
        )
        context.execute_async_v3(0)
        # Sonucu geri almaya gerek yok, warmup

    cudart.cudaDeviceSynchronize()

    # Asıl ölçüm
    start = time.perf_counter()
    for _ in range(n_runs):
        cudart.cudaMemcpy(
            d_input,
            x.ctypes.data,
            input_nbytes,
            cudart.cudaMemcpyKind.cudaMemcpyHostToDevice
        )
        context.execute_async_v3(0)
        # İstersen buraya DeviceToHost da ekleyebilirsin
    cudart.cudaDeviceSynchronize()
    end = time.perf_counter()

    total_time = end - start          # saniye
    avg_latency_ms = (total_time / n_runs) * 1000.0
    batch_size = input_shape[0]
    throughput = (batch_size * n_runs) / total_time   # FPS

    # GPU memory free
    cudart.cudaFree(d_input)
    cudart.cudaFree(d_output)

    return avg_latency_ms, throughput

import tensorrt as trt
import numpy as np
import os

onnx_file = "MobileNet-v2.onnx"

fp32_engine = "MobileNet-v2-fp32.engine"
fp16_engine = "MobileNet-v2-fp16.engine"
int8_engine = "MobileNet-v2-int8.engine"

logger = trt.Logger(trt.Logger.INFO)
builder = trt.Builder(logger)

# EXPLICIT_BATCH
explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
network = builder.create_network(explicit_batch_flag)
parser = trt.OnnxParser(network, logger)


# -------------------------------
# Load ONNX
# -------------------------------
print("Parsing ONNX...")
with open(onnx_file, "rb") as f:
    if not parser.parse(f.read()):
        print("ERROR: ONNX parse failed")
        for i in range(parser.num_errors):
            print(parser.get_error(i))
        raise SystemExit


# ================================================================
# 1) FP32 ENGINE
# ================================================================
print("\n=== Building FP32 engine ===")

config_fp32 = builder.create_builder_config()
config_fp32.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)  # 1GB

engine_fp32 = builder.build_serialized_network(network, config_fp32)
with open(fp32_engine, "wb") as f:
    f.write(engine_fp32)

print("Saved:", fp32_engine)


# ================================================================
# 2) FP16 ENGINE
# ================================================================
print("\n=== Building FP16 engine ===")

config_fp16 = builder.create_builder_config()
config_fp16.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)

config_fp16.set_flag(trt.BuilderFlag.FP16)

engine_fp16 = builder.build_serialized_network(network, config_fp16)
with open(fp16_engine, "wb") as f:
    f.write(engine_fp16)

print("Saved:", fp16_engine)




print("\n=== ALL ENGINES GENERATED SUCCESSFULLY ===")

import tensorrt as trt
from cuda import cudart
import numpy as np
import time

# Sadece FP32 ve FP16
ENGINES = {
    "FP32": "MobileNet-v2-fp32.engine",
    "FP16": "MobileNet-v2-fp16.engine"
}

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

def benchmark_engine(engine_path, name, iterations=1000):
    print(f"\n=== Benchmarking {name} ===")

    # Load engine
    with open(engine_path, "rb") as f:
        runtime = trt.Runtime(TRT_LOGGER)
        engine = runtime.deserialize_cuda_engine(f.read())

    context = engine.create_execution_context()

    # Detect input tensor
    input_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT
    ][0]

    output_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT
    ][0]

    # Shapes
    input_shape = tuple(engine.get_tensor_shape(input_name))
    output_shape = tuple(engine.get_tensor_shape(output_name))

    # Allocate GPU memory
    input_nbytes = np.prod(input_shape) * 4
    output_nbytes = np.prod(output_shape) * 4

    _, d_input = cudart.cudaMalloc(input_nbytes)
    _, d_output = cudart.cudaMalloc(output_nbytes)

    # Dummy input
    x = np.random.rand(*input_shape).astype(np.float32)

    cudart.cudaMemcpy(d_input, x.ctypes.data, input_nbytes,
                      cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)

    # Warmup
    for _ in range(20):
        context.set_tensor_address(input_name, d_input)
        context.set_tensor_address(output_name, d_output)
        context.execute_async_v3(0)

    # Benchmark loop
    start = time.time()
    for _ in range(iterations):
        context.execute_async_v3(0)
    end = time.time()

    total_ms = (end - start) * 1000
    avg_latency = total_ms / iterations
    throughput = 1000 / avg_latency

    return avg_latency, throughput


# Run benchmarks
results = []

for name, engine_file in ENGINES.items():
    latency, fps = benchmark_engine(engine_file, name)
    results.append((name, latency, fps))

# Print results
print("\n\n=== FINAL RESULTS ===")
print(f"{'Engine':<10} {'Latency (ms)':<15} {'Throughput (FPS)':<20}")
for name, lat, fps in results:
    print(f"{name:<10} {lat:<15.4f} {fps:<20.2f}")

import tensorrt as trt
from cuda import cudart
import numpy as np
import time

ENGINES = {
    "FP32": "MobileNet-v2-fp32.engine",
    "FP16": "MobileNet-v2-fp16.engine"
}

BATCH_SIZES = [1, 2, 4, 8, 16, 32, 64]

TRT_LOGGER = trt.Logger()


def benchmark_batch(engine_path, precision, batch_size, iterations=300):

    with open(engine_path, "rb") as f:
        runtime = trt.Runtime(TRT_LOGGER)
        engine = runtime.deserialize_cuda_engine(f.read())

    context = engine.create_execution_context()

    # Tensor names
    input_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT
    ][0]

    output_name = [
        engine.get_tensor_name(i)
        for i in range(engine.num_io_tensors)
        if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT
    ][0]

    # Replace batch dimension
    in_shape = list(engine.get_tensor_shape(input_name))
    in_shape[0] = batch_size
    input_shape = tuple(in_shape)

    out_shape = list(engine.get_tensor_shape(output_name))
    out_shape[0] = batch_size
    output_shape = tuple(out_shape)

    # Allocate GPU memory
    input_nbytes = np.prod(input_shape) * 4
    output_nbytes = np.prod(output_shape) * 4

    _, d_in = cudart.cudaMalloc(input_nbytes)
    _, d_out = cudart.cudaMalloc(output_nbytes)

    # Dummy batch
    dummy = np.random.rand(*input_shape).astype(np.float32)
    cudart.cudaMemcpy(d_in, dummy.ctypes.data, input_nbytes,
                      cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)

    # Warmup
    for _ in range(20):
        context.set_tensor_address(input_name, d_in)
        context.set_tensor_address(output_name, d_out)
        context.execute_async_v3(0)

    # Benchmark
    start = time.time()
    for _ in range(iterations):
        context.execute_async_v3(0)
    end = time.time()

    total_ms = (end - start) * 1000
    avg_latency = total_ms / iterations  # batch latency
    per_image_latency = avg_latency / batch_size
    throughput = (batch_size * 1000) / avg_latency

    return avg_latency, per_image_latency, throughput



# Run all benchmarks
results = []

for precision, engine_path in ENGINES.items():
    print(f"\n===== {precision} Benchmarks =====")
    for bs in BATCH_SIZES:
        avg_lat, per_lat, fps = benchmark_batch(engine_path, precision, bs)
        results.append((precision, bs, avg_lat, per_lat, fps))
        print(f"Batch {bs}:  Batch Lat = {avg_lat:.3f} ms,  Per-img = {per_lat:.4f} ms,  FPS = {fps:.1f}")


# Final table
print("\n\n=== FINAL TABLE ===")
print(f"{'Prec':<6}{'BS':<6}{'BatchLat(ms)':<15}{'PerImg(ms)':<12}{'FPS':<10}")
for r in results:
    print(f"{r[0]:<6}{r[1]:<6}{r[2]:<15.3f}{r[3]:<12.4f}{r[4]:<10.1f}")

import matplotlib.pyplot as plt
import numpy as np

# Batch sizes
batch_sizes = np.array([1, 2, 4, 8, 16, 32, 64])

# FP32 results (your measurements)
fp32_latency = np.array([0.475, 0.366, 0.365, 0.368, 0.366, 0.366, 0.370])
fp32_fps = np.array([2104.5, 5468.3, 10947.9, 21730.3, 43762.1, 87515.6, 172975.1])

# FP16 results
fp16_latency = np.array([0.297, 0.294, 0.294, 0.294, 0.294, 0.294, 0.294])
fp16_fps = np.array([3372.1, 6806.8, 13606.4, 27220.0, 54384.4, 108767.9, 217834.6])


# ================================
# 1. LATENCY GRAPH
# ================================
plt.figure(figsize=(10,6))
plt.plot(batch_sizes, fp32_latency, marker='o', label="FP32 Latency")
plt.plot(batch_sizes, fp16_latency, marker='o', label="FP16 Latency")

plt.title("Latency vs Batch Size (FP32 vs FP16)")
plt.xlabel("Batch Size")
plt.ylabel("Latency (ms)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()


# ================================
# 2. THROUGHPUT GRAPH
# ================================
plt.figure(figsize=(10,6))
plt.plot(batch_sizes, fp32_fps, marker='o', label="FP32 FPS")
plt.plot(batch_sizes, fp16_fps, marker='o', label="FP16 FPS")

plt.title("Throughput vs Batch Size (FP32 vs FP16)")
plt.xlabel("Batch Size")
plt.ylabel("Throughput (FPS)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()


import matplotlib.pyplot as plt

batch_sizes = [1, 2, 4, 8, 16, 32, 64]

fp32_lat = [0.475, 0.366, 0.365, 0.368, 0.366, 0.366, 0.370]
fp16_lat = [0.297, 0.294, 0.294, 0.294, 0.294, 0.294, 0.294]

speedup = [fp32_lat[i] / fp16_lat[i] for i in range(len(batch_sizes))]

plt.figure(figsize=(8,5))
plt.plot(batch_sizes, speedup, marker='o', linewidth=2)
plt.title("FP16 Speedup Over FP32")
plt.xlabel("Batch Size")
plt.ylabel("Speedup (×)")
plt.grid(True)
plt.show()


fp32_perimg = [0.4752, 0.1829, 0.0913, 0.0460, 0.0229, 0.0114, 0.0058]
fp16_perimg = [0.2965, 0.1469, 0.0735, 0.0367, 0.0184, 0.0092, 0.0046]

plt.figure(figsize=(8,5))
plt.plot(batch_sizes, fp32_perimg, marker='o', label="FP32 Per-Image Latency")
plt.plot(batch_sizes, fp16_perimg, marker='o', label="FP16 Per-Image Latency")
plt.title("Per-Image Latency vs Batch Size (FP32 vs FP16)")
plt.xlabel("Batch Size")
plt.ylabel("Latency per image (ms)")
plt.grid(True)
plt.legend()
plt.show()


plt.figure(figsize=(8,5))
plt.plot(batch_sizes, fp32_lat, marker='o', label="FP32 Batch Latency")
plt.plot(batch_sizes, fp16_lat, marker='o', label="FP16 Batch Latency")
plt.title("Batch Latency Flattening (GPU Saturation Effect)")
plt.xlabel("Batch Size")
plt.ylabel("Batch Latency (ms)")
plt.grid(True)
plt.legend()
plt.show()

import torch
import time
import numpy as np
import onnxruntime as ort
import tensorrt as trt
from cuda import cudart

# -----------------------------------
#  Create dummy input (BS=1)
# -----------------------------------
dummy = np.random.randn(1, 3, 224, 224).astype(np.float32)


# ================================
# 1. PyTorch Inference Benchmark
# ================================
import torchvision.models as models

model = models.mobilenet_v2(weights=None)
model.eval()

dummy_torch = torch.from_numpy(dummy)

# Warmup
for _ in range(20):
    model(dummy_torch)

# Benchmark
t0 = time.time()
iters = 500
for _ in range(iters):
    model(dummy_torch)
t1 = time.time()

pytorch_latency = (t1 - t0) * 1000 / iters
pytorch_fps = 1000 / pytorch_latency

print("PyTorch Latency:", pytorch_latency, "ms")
print("PyTorch FPS:", pytorch_fps)


# ================================
# 2. ONNX Runtime Benchmark
# ================================
ort_session = ort.InferenceSession("MobileNet-v2.onnx", providers=["CPUExecutionProvider"])

ort_inputs = {ort_session.get_inputs()[0].name: dummy}

# Warmup
for _ in range(20):
    ort_session.run(None, ort_inputs)

# Benchmark
t0 = time.time()
for _ in range(iters):
    ort_session.run(None, ort_inputs)
t1 = time.time()

ort_latency = (t1 - t0) * 1000 / iters
ort_fps = 1000 / ort_latency

print("ONNX Runtime Latency:", ort_latency, "ms")
print("ONNX Runtime FPS:", ort_fps)


# ================================
# 3. TensorRT Benchmark (FP16)
# ================================
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)

with open("MobileNet-v2-fp16.engine", "rb") as f:
    runtime = trt.Runtime(TRT_LOGGER)
    engine = runtime.deserialize_cuda_engine(f.read())

context = engine.create_execution_context()

input_name = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)
              if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT][0]

output_name = [engine.get_tensor_name(i) for i in range(engine.num_io_tensors)
               if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT][0]

input_shape = tuple(engine.get_tensor_shape(input_name))
output_shape = tuple(engine.get_tensor_shape(output_name))

# GPU memory
input_nbytes = np.prod(input_shape) * 4
output_nbytes = np.prod(output_shape) * 4

_, d_input = cudart.cudaMalloc(input_nbytes)
_, d_output = cudart.cudaMalloc(output_nbytes)

# Copy once
cudart.cudaMemcpy(d_input, dummy.ctypes.data, input_nbytes, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)

# Warmup
for _ in range(20):
    context.set_tensor_address(input_name, d_input)
    context.set_tensor_address(output_name, d_output)
    context.execute_async_v3(0)

# Benchmark
t0 = time.time()
for _ in range(iters):
    context.execute_async_v3(0)
t1 = time.time()

trt_latency = (t1 - t0) * 1000 / iters
trt_fps = 1000 / trt_latency

print("TensorRT FP16 Latency:", trt_latency, "ms")
print("TensorRT FP16 FPS:", trt_fps)

import matplotlib.pyplot as plt

# Your benchmark results
frameworks = ["PyTorch", "ONNX Runtime", "TensorRT FP16"]
latencies = [20.456, 2.482, 0.391]  # ms

plt.figure(figsize=(8,5))
plt.bar(frameworks, latencies, color=["red", "orange", "green"])
plt.ylabel("Latency (ms)")
plt.title("Latency Comparison (Batch = 1)")
plt.grid(axis="y", linestyle="--", alpha=0.5)

for i, v in enumerate(latencies):
    plt.text(i, v + 0.3, f"{v:.3f} ms", ha='center', fontsize=10)

plt.show()

import matplotlib.pyplot as plt

labels = ["TRT / PyTorch", "TRT / ONNX"]
speedups = [20.456 / 0.391, 2.482 / 0.391]

plt.figure(figsize=(7,5))
plt.bar(labels, speedups, color=["blue", "purple"])
plt.ylabel("Speedup (×)")
plt.title("TensorRT Speedup Over Other Frameworks (Batch = 1)")
plt.grid(axis="y", linestyle="--", alpha=0.5)

for i, v in enumerate(speedups):
    plt.text(i, v + 1, f"{v:.2f}×", ha='center', fontsize=12)

plt.show()

!sudo dpkg -i NsightSystems-linux-cli-public-2025.6.1.190-3689520.deb

!nsys --version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile trt_inference.py
# from cuda import cudart
# import numpy as np
# import time
# import cv2
# import tensorrt as trt
# import os
# 
# engine_path = "MobileNet-v2.engine"
# 
# TRT_LOGGER = trt.Logger()
# runtime = trt.Runtime(TRT_LOGGER)
# 
# with open(engine_path, "rb") as f:
#     engine = runtime.deserialize_cuda_engine(f.read())
# 
# context = engine.create_execution_context()
# 
# input_name = [engine.get_tensor_name(i)
#               for i in range(engine.num_io_tensors)
#               if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.INPUT][0]
# 
# output_name = [engine.get_tensor_name(i)
#                for i in range(engine.num_io_tensors)
#                if engine.get_tensor_mode(engine.get_tensor_name(i)) == trt.TensorIOMode.OUTPUT][0]
# 
# output_shape = tuple(engine.get_tensor_shape(output_name))
# 
# # Allocate memory
# input_nbytes = 1 * 3 * 224 * 224 * 4
# output_nbytes = np.prod(output_shape) * 4
# 
# _, d_input = cudart.cudaMalloc(input_nbytes)
# _, d_output = cudart.cudaMalloc(output_nbytes)
# 
# # Dummy input
# x = np.random.rand(1,3,224,224).astype(np.float32)
# 
# # Warm up
# for _ in range(5):
#     cudart.cudaMemcpy(d_input, x.ctypes.data, input_nbytes,
#                       cudart.cudaMemcpyKind.cudaMemcpyHostToDevice)
#     context.set_tensor_address(input_name, d_input)
#     context.set_tensor_address(output_name, d_output)
#     context.execute_async_v3(0)
#

!nsys profile -o mobilenet_report python3 trt_inference.py

import tensorrt as trt

onnx_file = "MobileNet-v2.onnx"

# VERBOSE logger şart
logger = trt.Logger(trt.Logger.VERBOSE)
builder = trt.Builder(logger)

# EXPLICIT batch
explicit_batch_flag = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
network = builder.create_network(explicit_batch_flag)
parser = trt.OnnxParser(network, logger)

# Parse ONNX
with open(onnx_file, "rb") as f:
    parser.parse(f.read())


def build_engine(fp16=False, name="engine.trt"):
    config = builder.create_builder_config()
    config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)

    # ENABLING TACTIC, FUSION, KERNEL, WORKSPACE LOGGING
    config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED

    if fp16:
        print("\n=== BUILDING FP16 ENGINE ===")
        config.set_flag(trt.BuilderFlag.FP16)
    else:
        print("\n=== BUILDING FP32 ENGINE ===")

    engine_serialized = builder.build_serialized_network(network, config)

    with open(name, "wb") as f:
        f.write(engine_serialized)

    print("Saved:", name)


# Build FP32
build_engine(fp16=False, name="mobilenet_fp32.engine")

# Build FP16
build_engine(fp16=True, name="mobilenet_fp16.engine")

!pip install ninja

import os, torch
from torch.utils.cpp_extension import load

# 🔑 BU SATIR EKSİKTİ
os.makedirs("/content/torch_extensions/dwext", exist_ok=True)

src_cuda = r"""
#include <torch/extension.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_fp16.h>

__global__ void dwconv3x3_fp16_kernel(
    const half* __restrict__ x,
    const half* __restrict__ w,
    half* __restrict__ y,
    int N, int C, int H, int W
){
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    int total = N * C * H * W;
    if (tid >= total) return;

    int t = tid;
    int w0 = t % W; t /= W;
    int h0 = t % H; t /= H;
    int c  = t % C; t /= C;
    int n  = t;

    const half* wc = w + c * 9;

    float acc = 0.0f;
    #pragma unroll
    for (int kh = -1; kh <= 1; kh++) {
        #pragma unroll
        for (int kw = -1; kw <= 1; kw++) {
            int h = h0 + kh;
            int ww = w0 + kw;
            if ((unsigned)h < (unsigned)H && (unsigned)ww < (unsigned)W) {
                float xv = __half2float(x[((n*C + c)*H + h)*W + ww]);
                float wv = __half2float(wc[(kh+1)*3 + (kw+1)]);
                acc += xv * wv;
            }
        }
    }
    y[((n*C + c)*H + h0)*W + w0] = __float2half(acc);
}

torch::Tensor dwconv3x3_fp16(torch::Tensor x, torch::Tensor w) {
    TORCH_CHECK(x.is_cuda(), "x must be CUDA");
    TORCH_CHECK(w.is_cuda(), "w must be CUDA");
    TORCH_CHECK(x.scalar_type() == at::kHalf, "x must be FP16");
    TORCH_CHECK(w.scalar_type() == at::kHalf, "w must be FP16");

    int N = x.size(0);
    int C = x.size(1);
    int H = x.size(2);
    int W = x.size(3);

    auto y = torch::empty_like(x);

    int total = N*C*H*W;
    int threads = 256;
    int blocks = (total + threads - 1) / threads;

    dwconv3x3_fp16_kernel<<<blocks, threads>>>(
        (half*)x.data_ptr<at::Half>(),
        (half*)w.data_ptr<at::Half>(),
        (half*)y.data_ptr<at::Half>(),
        N, C, H, W
    );

    return y;
}
"""

src_cpp = r"""
#include <torch/extension.h>
torch::Tensor dwconv3x3_fp16(torch::Tensor x, torch::Tensor w);

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("dwconv3x3_fp16", &dwconv3x3_fp16, "Depthwise 3x3 FP16 (CUDA)");
}
"""

os.makedirs("dwext", exist_ok=True)
with open("dwext/dwconv.cu", "w") as f: f.write(src_cuda)
with open("dwext/bind.cpp", "w") as f: f.write(src_cpp)

dwext = load(
    name="dwext",
    sources=["dwext/bind.cpp", "dwext/dwconv.cu"],
    build_directory="/content/dwext",
    extra_cflags=["-O3"],
    extra_cuda_cflags=["--use_fast_math", "-lineinfo"],
    with_cuda=True,
    verbose=True,
)

print("Built extension:", dwext)

import torch
import torch.nn.functional as F

N, C, H, W = 1, 32, 112, 112
x = torch.randn(N, C, H, W, device="cuda", dtype=torch.float16)
w = torch.randn(C, 1, 3, 3, device="cuda", dtype=torch.float16)

y_pt = F.conv2d(x, w, None, 1, 1, 1, C)
y_cu = dwext.dwconv3x3_fp16(x, w)

print("max abs diff:", (y_pt - y_cu).abs().max().item())

import torch
import torch.nn.functional as F

def bench(fn, warmup=200, iters=2000):
    # warmup
    for _ in range(warmup):
        fn()
    torch.cuda.synchronize()

    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

    start.record()
    for _ in range(iters):
        fn()
    end.record()

    torch.cuda.synchronize()
    total_ms = start.elapsed_time(end)
    return total_ms / iters  # ms per iteration

torch.backends.cudnn.benchmark = True

N, C, H, W = 1, 32, 112, 112
x = torch.randn(N, C, H, W, device="cuda", dtype=torch.float16)
w = torch.randn(C, 1, 3, 3, device="cuda", dtype=torch.float16)

t_pt = bench(lambda: F.conv2d(x, w, None, 1, 1, 1, C))
print(f"PyTorch FP16 depthwise conv: {t_pt:.6f} ms")

t_cu = bench(lambda: dwext.dwconv3x3_fp16(x, w))
print(f"Custom CUDA kernel: {t_cu:.6f} ms")

speedup = t_pt / t_cu
print(f"Speedup (PyTorch / Custom): {speedup:.2f}×")

shapes = [
    (1, 16, 112, 112),
    (1, 32, 56, 56),
    (1, 64, 28, 28),
]

results = []

for (N, C, H, W) in shapes:
    x = torch.randn(N, C, H, W, device="cuda", dtype=torch.float16)
    w = torch.randn(C, 1, 3, 3, device="cuda", dtype=torch.float16)

    t_pt = bench(lambda: F.conv2d(x, w, None, 1, 1, 1, C))
    t_cu = bench(lambda: dwext.dwconv3x3_fp16(x, w))

    results.append((C, H, W, t_pt, t_cu, t_pt / t_cu))

for r in results:
    print(f"C={r[0]:3d}, H=W={r[1]:3d} | PT={r[3]:.6f} ms | CU={r[4]:.6f} ms | speedup={r[5]:.2f}×")

import matplotlib.pyplot as plt

# Measured results
labels = [
    "C=16, 112×112",
    "C=32, 56×56",
    "C=64, 28×28"
]

speedups = [1.62, 1.88, 1.99]

plt.figure(figsize=(7, 5))
plt.bar(labels, speedups)
plt.ylabel("Speedup (×)")
plt.xlabel("Depthwise Convolution Layer")
plt.title("Custom CUDA Kernel Speedup over PyTorch FP16 Depthwise Conv")

# annotate bars
for i, v in enumerate(speedups):
    plt.text(i, v + 0.03, f"{v:.2f}×", ha="center", fontsize=11)

plt.ylim(0, max(speedups) + 0.4)
plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

results = [
    (16, 112, 0.015533, 0.009559),
    (32, 56,  0.018366, 0.009745),
    (64, 28,  0.019082, 0.009580),
]

for C, HW, pt, cu in results:
    pt_tp = 1.0 / (pt * 1e-3)
    cu_tp = 1.0 / (cu * 1e-3)
    print(f"C={C}, H=W={HW} | "
          f"PT throughput={pt_tp:.0f}/s | "
          f"CU throughput={cu_tp:.0f}/s | "
          f"speedup={pt/cu:.2f}×")

import os, torch
from torch.utils.cpp_extension import load

# Build directory
os.makedirs("/content/torch_extensions/pwext", exist_ok=True)
os.makedirs("pwext", exist_ok=True)

# ============================
# CUDA source
# ============================
src_cuda = r"""
#include <torch/extension.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_fp16.h>

__global__ void pwconv1x1_fp16_kernel(
    const half* __restrict__ x,
    const half* __restrict__ w,
    half* __restrict__ y,
    int N, int Cin, int Cout, int H, int W
){
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    int total = N * Cout * H * W;
    if (tid >= total) return;

    int t = tid;
    int w0 = t % W; t /= W;
    int h0 = t % H; t /= H;
    int co = t % Cout; t /= Cout;
    int n  = t;

    float acc = 0.f;
    const half* w_row = w + co * Cin;

    for (int ci = 0; ci < Cin; ci++) {
        float xv = __half2float(x[((n*Cin + ci)*H + h0)*W + w0]);
        float wv = __half2float(w_row[ci]);
        acc += xv * wv;
    }

    y[((n*Cout + co)*H + h0)*W + w0] = __float2half(acc);
}

torch::Tensor pwconv1x1_fp16(torch::Tensor x, torch::Tensor w) {
    TORCH_CHECK(x.is_cuda(), "x must be CUDA");
    TORCH_CHECK(w.is_cuda(), "w must be CUDA");
    TORCH_CHECK(x.scalar_type() == at::kHalf, "x must be FP16");
    TORCH_CHECK(w.scalar_type() == at::kHalf, "w must be FP16");
    TORCH_CHECK(x.dim() == 4, "x must be NCHW");
    TORCH_CHECK(w.dim() == 4, "w must be [Cout, Cin, 1, 1]");

    int N = x.size(0);
    int Cin = x.size(1);
    int H = x.size(2);
    int W = x.size(3);
    int Cout = w.size(0);

    auto y = torch::empty({N, Cout, H, W}, x.options());

    int total = N * Cout * H * W;
    int threads = 256;
    int blocks = (total + threads - 1) / threads;

    pwconv1x1_fp16_kernel<<<blocks, threads>>>(
        (half*)x.data_ptr<at::Half>(),
        (half*)w.data_ptr<at::Half>(),
        (half*)y.data_ptr<at::Half>(),
        N, Cin, Cout, H, W
    );

    return y;
}
"""

# ============================
# C++ binding
# ============================
src_cpp = r"""
#include <torch/extension.h>

torch::Tensor pwconv1x1_fp16(torch::Tensor x, torch::Tensor w);

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("pwconv1x1_fp16", &pwconv1x1_fp16, "Pointwise 1x1 FP16 (CUDA)");
}
"""

# Write sources
with open("pwext/pwconv.cu", "w") as f:
    f.write(src_cuda)

with open("pwext/bind.cpp", "w") as f:
    f.write(src_cpp)

# ============================
# Build & load extension
# ============================
pwext = load(
    name="pwext",
    sources=["pwext/bind.cpp", "pwext/pwconv.cu"],
    build_directory="/content/torch_extensions/pwext",
    extra_cflags=["-O3"],
    extra_cuda_cflags=["--use_fast_math", "-lineinfo"],
    with_cuda=True,
    verbose=True,
)

print("✅ Pointwise extension loaded:", pwext)

import torch.nn.functional as F

x = torch.randn(1, 64, 56, 56, device="cuda", dtype=torch.float16)

# DOĞRU weight shape
w = torch.randn(64, 64, 1, 1, device="cuda", dtype=torch.float16)

# PyTorch
y_pt = F.conv2d(x, w)

# Custom CUDA
y_cu = pwext.pwconv1x1_fp16(x, w)

print("Max abs diff:", (y_pt - y_cu).abs().max().item())

import torch
import torch.nn.functional as F

def bench(fn, warmup=100, iters=1000):
    for _ in range(warmup):
        fn()
    torch.cuda.synchronize()

    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

    start.record()
    for _ in range(iters):
        fn()
    end.record()

    torch.cuda.synchronize()
    return start.elapsed_time(end) / iters  # ms


# -------------------------
# Shapes
# -------------------------
B, Cin, Cout, H, W = 1, 32, 64, 56, 56

x = torch.randn(B, Cin, H, W, device="cuda", dtype=torch.float16)

# 🔑 DOĞRU weight shape
w = torch.randn(Cout, Cin, 1, 1, device="cuda", dtype=torch.float16)

# -------------------------
# Benchmarks
# -------------------------
t_pt = bench(lambda: F.conv2d(x, w))
t_cu = bench(lambda: pwext.pwconv1x1_fp16(x, w))

pt_tp = B / (t_pt * 1e-3)
cu_tp = B / (t_cu * 1e-3)

print(f"Pointwise PT latency: {t_pt:.4f} ms")
print(f"Pointwise CU latency: {t_cu:.4f} ms")
print(f"PT throughput: {pt_tp:.0f} samples/s")
print(f"CU throughput: {cu_tp:.0f} samples/s")
print(f"Speedup: {t_pt / t_cu:.2f}×")

import torch
import time
import pandas as pd
import matplotlib.pyplot as plt

torch.backends.cudnn.benchmark = True
device = "cuda"

# ----------------------------
# Benchmark helpers
# ----------------------------
def benchmark_pytorch(x, w, iters=200, warmup=50):
    conv = torch.nn.Conv2d(
        x.shape[1], x.shape[1], kernel_size=1, bias=False
    ).to(device).half()
    conv.weight.data.copy_(w)

    # warmup
    for _ in range(warmup):
        _ = conv(x)

    torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(iters):
        _ = conv(x)
    torch.cuda.synchronize()
    t1 = time.time()

    return (t1 - t0) * 1000 / iters


def benchmark_custom(x, w, iters=200, warmup=50):
    # warmup
    for _ in range(warmup):
        _ = pwext.pwconv1x1_fp16(x, w)

    torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(iters):
        _ = pwext.pwconv1x1_fp16(x, w)
    torch.cuda.synchronize()
    t1 = time.time()

    return (t1 - t0) * 1000 / iters


# ----------------------------
# Run benchmarks
# ----------------------------
channels = [16, 32, 64, 128]
results = []

N, H, W = 1, 56, 56

for C in channels:
    print(f"\n🔍 Benchmarking C={C}")

    x = torch.randn(N, C, H, W, device=device, dtype=torch.float16)
    w = torch.randn(C, C, 1, 1, device=device, dtype=torch.float16)

    pt_latency = benchmark_pytorch(x, w)
    cu_latency = benchmark_custom(x, w)

    pt_tp = 1000 / pt_latency
    cu_tp = 1000 / cu_latency
    speedup = pt_latency / cu_latency

    results.append([
        C, pt_latency, cu_latency, pt_tp, cu_tp, speedup
    ])

    print(
        f"C={C:4d} | "
        f"PT={pt_latency:.4f} ms | "
        f"CU={cu_latency:.4f} ms | "
        f"Speedup={speedup:.2f}×"
    )

# ----------------------------
# Results table
# ----------------------------
df = pd.DataFrame(
    results,
    columns=[
        "Channels",
        "PyTorch Latency (ms)",
        "Custom CUDA Latency (ms)",
        "PyTorch Throughput (samples/s)",
        "Custom CUDA Throughput (samples/s)",
        "Speedup"
    ]
)

df

plt.figure(figsize=(7,4))
plt.plot(df["Channels"], df["Speedup"], marker="o")
plt.xlabel("Channel Count (Cin = Cout)")
plt.ylabel("Speedup (PyTorch / Custom)")
plt.title("Pointwise 1×1 Convolution Speedup vs Channel Count")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

shapes = [
    (1, 16, 112, 112),
    (1, 32, 56, 56),
    (1, 64, 28, 28),
]

results = []

for (N, C, H, W) in shapes:
    x = torch.randn(N, C, H, W, device="cuda", dtype=torch.float16)
    w = torch.randn(C, 1, 3, 3, device="cuda", dtype=torch.float16)

    t_pt = bench(lambda: F.conv2d(x, w, None, 1, 1, 1, C))
    t_cu = bench(lambda: dwext.dwconv3x3_fp16(x, w))

    results.append((C, H, W, t_pt, t_cu, t_pt / t_cu))

for r in results:
    print(f"C={r[0]:3d}, H=W={r[1]:3d} | PT={r[3]:.6f} ms | CU={r[4]:.6f} ms | speedup={r[5]:.2f}×")

import torch
import torch.nn.functional as F

# MobileNetV2 tipik pointwise shape'leri
shapes = [
    (1, 16, 112, 112),
    (1, 32, 56, 56),
    (1, 64, 28, 28),
]

results = []

for (N, C, H, W) in shapes:
    print(f"\nBenchmarking Pointwise: C={C}, H=W={H}")

    x = torch.randn(N, C, H, W, device="cuda", dtype=torch.float16)

    # Pointwise weight
    w = torch.randn(C, C, 1, 1, device="cuda", dtype=torch.float16)

    # PyTorch
    t_pt = bench(lambda: F.conv2d(x, w))        # ms

    # Custom CUDA
    t_cu = bench(lambda: pwext.pwconv1x1_fp16(x, w))  # ms

    # Throughput (samples / second)
    pt_tp = N / (t_pt * 1e-3)
    cu_tp = N / (t_cu * 1e-3)

    speedup = t_pt / t_cu

    results.append((C, H, W, t_pt, t_cu, pt_tp, cu_tp, speedup))


# Sonuçları yazdır
for r in results:
    print(
        f"C={r[0]:3d}, H=W={r[1]:3d} | "
        f"PT={r[3]:.6f} ms | "
        f"CU={r[4]:.6f} ms | "
        f"PT tp={r[5]:.0f}/s | "
        f"CU tp={r[6]:.0f}/s | "
        f"speedup={r[7]:.2f}×"
    )